### ISSUE TITLE
Crashes out after first pkg install

### ISSUE THREAD

**Issue by sramdeen** [carlashley/appleloops#2]
**Describe the bug**
appleloops crashes out after the initial install of a content package.

appleloops --deployment -m --log-level DEBUG
Analysing...
Mandatory packages download/install size: 2.46 GB/3.06 GB (45 packages)
All packages download/install size: 2.46 GB/3.06 GB (45) packages

Downloading https://audiocontentdownload.apple.com/lp10_ms3_content_2016/MAContent10_AssetPack_0092_AlchemyBassMini3VCOSquares.pkg
######################################################################## 100.0%
Installing MAContent10_AssetPack_0092_AlchemyBassMini3VCOSquares.pkg
  Installed MAContent10_AssetPack_0092_AlchemyBassMini3VCOSquares.pkg
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/appleloops/__main__.py", line 151, in <module>
  File "/usr/local/bin/appleloops/__main__.py", line 130, in main
  File "/usr/local/bin/appleloops/loopslib/deployment.py", line 151, in process
  File "/usr/local/bin/appleloops/loopslib/misc.py", line 100, in clean_up
TypeError: coercing to Unicode: need string or buffer, LoopPackage found

Looking at the install.log, the package that is downloaded before the crash does install successfully and a subsequent run of appleloops forces it to move on to the next package that is required.

Running in download-only mode (no --deploy or --deployment), the packages appear to come down fine, one after the other.

**Version**
appleloops 3.0.0 (Apache License, Version 2.0)

sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87

python --version
Python 2.7.10

**Command Used**
appleloops --deployment -m --log-level DEBUG

**Debug Log**
[debug.log](https://github.com/carlashley/appleloops/files/3511251/debug.log)

**Comment by carlashley** [comment]
Thanks for the info. That should be resolved now in v3.0.1.
