### ISSUE TITLE
Python weirdness with 3.2.1

### ISSUE THREAD

**Issue by MiqViq** [carlashley/appleloops#27]
**Describe the bug**
appleloops v3.2.1 built 2020-11-15, Apache License, Version 2.0
appleloops -a mainstage -m -o --deployment
Traceback (most recent call last):
  File "/Library/Application Support/Python_3/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Application Support/Python_3/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/appleloops/__main__.py", line 180, in <module>
  File "/usr/local/bin/appleloops/__main__.py", line 77, in main
  File "/usr/local/bin/appleloops/loopslib/arguments.py", line 336, in parse_args
TypeError: 'NoneType' object is not subscriptable
**Version**
The version of `appleloops.py` used. Can be found by using `./appleloops.py --version`.

**Debug Log**
cat /var/log/appleloops.log
2020-12-09 16:21:37 - root - INFO - ------------------ Log opened on 2020-12-09 16:21:37 ------------------
2020-12-09 16:21:37 - loopslib.process_source - INFO - Installed apps found: MainStage 3 (3.5)
2020-12-09 16:22:28 - root - INFO - ------------------ Log closed on 2020-12-09 16:22:28 ------------------

Tested with Python 3.8.5 and 3.9.0, same issue.
appleloops 3.2.0 starts ok with either Python.

Maybe it cannot handle my path for Python?

**Comment by carlashley** [comment]
Upcoming release will address this.
