### ISSUE TITLE
Proxy Server option

### ISSUE THREAD

**Issue by jolegape** [carlashley/appleLoops#28]
Command Used: `sudo /usr/local/bin/appleLoops.py --deployment --mandatory-only --optional-only --dry-run`

My school is behind a district/diocesan wide internet filter that I have no control over. As a result this script fails with the error 

> Traceback (most recent call last):
>   File "/Users/admin/Downloads/appleLoops.py", line 1577, in <module>
>     main()
>   File "/Users/admin/Downloads/appleLoops.py", line 1414, in main
>     metavar=AppleLoops(help_init=True).supported_plists,
>   File "/Users/admin/Downloads/appleLoops.py", line 351, in __init__
>     self.exit('config_read', custom_msg=self.config_url)
> AttributeError: AppleLoops instance has no attribute 'config_url'

We have 1 IP allocated that can bypass the firewall that we run a squid proxy server on.
Hard coding the following starting at line 70 allows me to use my proxy server to install the Apple Loops.

```
proxyHandler = urllib2.ProxyHandler(
            {
            'http': '10.192.80.54:3129',
            'https': '10.192.80.54:3129',
            }
        )
        proxyOpener = urllib2.build_opener(proxyHandler)
        urllib2.install_opener(proxyOpener)
```

I am trying to add it as an argument that can be passed but am not having luck so far.

**Comment by leeramsay** [comment]
@jolegape can you set http/https_proxy env variables prior to running? Try the following:

```
export HTTP_PROXY=http://10.192.80.54:3129
export HTTPS_PROXY=http://10.192.80.54:3129
sudo /usr/local/bin/appleLoops.py --deployment --mandatory-only --optional-only --dry-run
```
