### ISSUE TITLE
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.

### ISSUE THREAD

**Issue by walkintom** [carlashley/appleloops#33]
**Describe the bug**
Receiving error messages `curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.` followed by the below python traceback errors.

`curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
Traceback (most recent call last):
  File "/Volumes/Data/appleloops-3.2.3.20210706/./appleloops/loopslib/deployment.py", line 178, in process
  File "/Volumes/Data/appleloops-3.2.3.20210706/./appleloops/loopslib/deployment.py", line 91, in _download
  File "/Volumes/Data/appleloops-3.2.3.20210706/./appleloops/loopslib/curl_requests.py", line 229, in get
  File "/Volumes/Data/appleloops-3.2.3.20210706/./appleloops/loopslib/curl_requests.py", line 226, in get
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--retry', '5', '--retry-max-time', '10', '--http1.1', '--user-agent', 'appleloops/3.2.2', '-L', '-C', '-', 'https://audiocontentdownload.apple.com/lp10_ms3_content_2016/MAContent10_AssetPack_0048_AlchemyPadsDigitalHolyGhost.pkg', '--progress-bar', '--create-dirs', '-o', '/Volumes/Data/munki_repo/pkgs/appleloops/lp10_ms3_content_2016/MAContent10_AssetPack_0048_AlchemyPadsDigitalHolyGhost.pkg']' returned non-zero exit status 33.`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Volumes/Data/appleloops-3.2.3.20210706/./appleloops/__main__.py", line 180, in <module>
  File "/Volumes/Data/appleloops-3.2.3.20210706/./appleloops/__main__.py", line 157, in main
  File "/Volumes/Data/appleloops-3.2.3.20210706/./appleloops/loopslib/deployment.py", line 180, in process
AttributeError: 'CalledProcessError' object has no attribute 'strip'`

**Version**
appleloops v3.2.2 built 2020-11-17, Apache License, Version 2.0

**Command Used**
`./appleloops --plists logicpro1050 -m -o -d /Volumes/Data/munki_repo/pkgs/appleloops -l DEBUG`

**Debug Log**
Attached.
[appleloops.log](https://github.com/carlashley/appleloops/files/6869154/appleloops.log)

**Comment by carlashley** [comment]
Try downloading the `3.2.3` dev release here and giving that a go: https://github.com/carlashley/appleloops/releases/tag/v3.2.3.20210706

**Comment by walkintom** [comment]
Weirdly enough, I thought I was using `3.2.3`. The download from the repo is labelled as such but the executable is showing as `3.2.2`. I'll redownload and check.

**Comment by walkintom** [comment]
Yeah, the version from `3.2.3` is coming out as `3.2.2`.

**Comment by carlashley** [comment]
Oh my bad, the dev release doesn't have a pre-built package... I'll update that later today.

**Comment by walkintom** [comment]
This appeared to be resolved when using the 3.2.3 pre-built package.
